### ISSUE TITLE
Use Managed Service Identity to auth to ACR

### ISSUE THREAD

**Issue by Jarlotee** [Azure/app-service-linux-docs#12]
Is it possible to use MSI assigned to the web app as the authentication mechanism to pull images from ACR?

**Comment by J0F3** [comment]
I have the same question. Any news?

**Comment by andrey-moor** [comment]
+1

**Comment by btardif** [comment]
Here are instructions: 
- [How to use system-assigned Managed Identities with App Service and Azure Container Registry](https://github.com/Azure/app-service-linux-docs/blob/master/HowTo/use_system-assigned_managed_identities.md)
- [How to use user-assigned Managed Identities with App Service and Azure Container Registry](https://github.com/Azure/app-service-linux-docs/blob/master/HowTo/use_user-assigned_managed_identities.md)

We are still working on making this simpler and UX support is scheduled for First Half 2021

CC: @Jarlotee @J0F3 @andrey-moor
