### ISSUE TITLE
is gRPC generally available or still in preview?

### ISSUE THREAD

**Issue by safari137** [Azure/app-service-linux-docs#145]
https://github.com/Azure/app-service-linux-docs/blob/master/HowTo/gRPC/README.md implies that it is GA

https://github.com/Azure/app-service-linux-docs/blob/master/HowTo/gRPC/use_gRPC_with_dotnet.md implies that it is in public preview

**Comment by jeffwmartinez** [comment]
I've updated the README to avoid further confusion.
