### ISSUE TITLE
Node support timeline

### ISSUE THREAD

**Issue by georgeOsdDev** [Azure/app-service-linux-docs#148]
We received mail from azure with the subject line [Community support for Node 16 LTS is ending on 11 September 2023, upgrade to Node 18 LTS]

Please update support time line table on below page

https://github.com/Azure/app-service-linux-docs/blob/master/Runtime_Support/node_support.md#support-timeline
<img width="339" alt="image" src="https://user-images.githubusercontent.com/1381907/204408650-00882d05-ee25-41d4-a5c4-183a5a978b23.png">

**Comment by jeffwmartinez** [comment]
Table has been updated.  Thank you
