### ISSUE TITLE
gRPC setup for .NET 7

### ISSUE THREAD

**Issue by georgeOsdDev** [Azure/app-service-linux-docs#149]
Please update gRPC server setup for .NET 7.
Currently when we select .NET 7(linuxFxVersion ="DOTNETCORE|7.0"), `Kestrel__Endpoints__***` environment variables are exported by App Service (oryx). This cause `address already in use` exception.As workaround, we did not need `ListenAnyIP(...)` from code.

https://github.com/Azure/app-service-linux-docs/blob/master/HowTo/gRPC/use_gRPC_with_dotnet.md

**Comment by jeffwmartinez** [comment]
New documentation is out for .NET 7 [here](https://github.com/Azure/app-service-linux-docs/tree/master/HowTo/gRPC/.NET/.NET%207) that doesn't require ListenAnyIp().  The original document is still valid for .NET 6.

**Comment by javorenator** [comment]
.NET 6 gRPC services are also broken, not pleasant at all. Now I see that .NET 6 documentation was also updated.

**Comment by erichfrazer** [comment]
yes this had me stumped for a hole two days. Leave the ListenAnyIP( ) stuff out of the server, and on the client, do NOT put in the port address when you're connecting to the server, it doesn't work if you do. Also remember to add the HTTP20_ONLY_PORT thing. This enabled me to run. For NOT connecting to Azure, the client DOES need to specify the port #. Confusing.
