### ISSUE TITLE
Azure App Service doesn't start

### ISSUE THREAD

**Issue by jameswoodley** [Azure/app-service-linux-docs#157]
I am using a Linux App Service, deploying a gRPC app, and it seems to never start. I followed all steps in the tutorial, and when looking at Log Stream for the app, I see

```
2023-01-15T12:37:21.967Z ERROR - Container <SITE_NAME>_0_0425d143_middleware for site <SITE_NAME> did not start within expected time limit. Elapsed time = 230.2349212 sec
2023-01-15T12:37:21.979Z ERROR - Container <SITE_NAME>_0_0425d143_middleware didn't respond to HTTP pings on port: 8181, failing site start. See container logs for debugging.
2023-01-15T12:37:22.008Z INFO  - Stopping site <SITE_NAME> because it failed during startup.
```

My App Service however shows a status of Running.

Code used in Program.cs is
```
builder.WebHost.ConfigureKestrel(options =>
    {
        options.ListenAnyIP(8080);
        options.ListenAnyIP(8585, listenOptions =>
        {
            listenOptions.Protocols = HttpProtocols.Http2;
        });
    });
```

And I have the configuration setting for HTTP 2.0 set
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/52610563/212541132-ba9472a4-a70d-41d4-b376-1b491ffa03bc.png">
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/52610563/212541151-83fda58c-a7d3-420f-9d37-5373ace7af14.png">

If I call my gRPC server from a client, I get a 403 error.

Is there something I'm missing, do I need to expose something on port 8181 to tell the container to start? (I am using Octopus Deploy for deployment, which I believe uses Zip Deploy, so the container is the Azure App Service, nothing to do with me)

Thanks!

**Comment by jameswoodley** [comment]
Yo thanks for the update. You pointed me along the right direction, using the docs for .net 7 actually got this working. I think it was the combination of the Kestrel set up and the ports for .net 6.

So conclusions, move to .net 7 if hosting gRPC in Azure 😆

**Comment by OakenKnight** [comment]
I'm glad it helped! :rocket:
