### ISSUE TITLE
Service Principal Authentication No Longer Works

### ISSUE THREAD

**Issue by jonmill** [Azure/app-service-linux-docs#2]
Hi,

Following the FAQ here: https://github.com/Azure/app-service-linux-docs/blob/master/service_principal_auth_acr.md 

No longer works; the Web App only seems to be able to pull from ACR when using the Admin user, not a Service Principal with AcrPull access. Should the docs be updated / is this a bug?

**Comment by jonmill** [comment]
@yiliaomsft

**Comment by yiliaomsft** [comment]
I verified it on my ACR images and it does work with the service principal auth. If you still see the issue, please open a support ticket so we can take a look.

**Comment by jonmill** [comment]
I filed a ticket with support; would you like the ticket number to follow up?

**Comment by yiliaomsft** [comment]
That will be good to have the ticket#.

**Comment by jonmill** [comment]
Sure, the case number is 119051322002439

**Comment by jonmill** [comment]
Issue resolved; looks like it was a template issue
