### ISSUE TITLE
Are dates on the Support timeline correct?

### ISSUE THREAD

**Issue by mrahl** [Azure/app-service-linux-docs#59]
The support timeline in https://github.com/Azure/app-service-linux-docs/blob/master/Runtime_Support/dot_net_core.md sets the end of support for .NET 5 to Feb 2023. This seems contradictory to the .NET support policy which sets the same date to "around Feb 2022": https://dotnet.microsoft.com/platform/support/policy/dotnet-core

Is .NET 5 in fact supported longer on App Service than "outside", is this an error, or is there another explanation?

**Comment by jeffwmartinez** [comment]
.NET 5 reached EOL on May 10th, 2022.  Closing.
