### ISSUE TITLE
Drupal 9 on Azure Linux App Service - running Drush commands

### ISSUE THREAD

**Issue by futuredesignUK** [Azure/app-service-linux-docs#83]
**Scenario:**

- Azure Linux App Service Plan B1
- Dev & Prod App Service (Kudu container)
- Drupal 9 application code 
- Azure DevOps CI/CD (composer installs drush)
- MySQL hosted on Azure VM

Drupal 9 website running just fine on Azure app service with AzDO deploying code to Dev and prod app services OK.

On local machine [Drush](https://github.com/drush-ops/drush) is used for command line updates (clear cache, update DB and config import/export)

When deploying to the App Services Drush does not work, as the command is not found, it is deployed to the vendor folder

This means the browser has to be used for all related commands which is manual, slow and prone to error.

Can Drush can be installed and enabled on the App Service Kudu Container?  this will complete the CI/CD automation. 

There doesn't seem to be alot on this topic:

https://sunithamk.wordpress.com/2014/04/01/drupal-running-drush-on-windows-azure-websites/

https://omgdebugging.com/2019/01/23/running-commands-inside-actual-web-container-in-azure-web-app-for-containers/

![image](https://user-images.githubusercontent.com/19208973/126473401-010a8f0a-c7c5-4c0a-adeb-f355bec07525.png)

```
root@298f2cb17543:/home/site/wwwroot/vendor/drush/drush# drush status
-bash: drush: command not found
```

![image](https://user-images.githubusercontent.com/19208973/126477582-d20bfd9b-3dc0-4da4-b2aa-a709be37b175.png)

**Comment by futuredesignUK** [comment]
Any updates?

**Comment by tapscola** [comment]
Has anyone got a solution with this yet?

**Comment by jakeburkart** [comment]
> Has anyone got a solution with this yet?

Login to SSH and run this:
`export PATH="/home/site/wwwroot/vendor/bin:$PATH"`

**Comment by futuredesignUK** [comment]
Nice job @jakeburkart  - works!

![image](https://user-images.githubusercontent.com/19208973/229303217-461d7acd-d2d6-4699-9daa-6177a8336e48.png)

**Comment by jakeburkart** [comment]
You do have to run that export path command every time you login though. There’s probably a way to have a shell script run on login, but I haven’t gotten there yet.

**Comment by tapscola** [comment]
Brilliant thanks lots!
