### ISSUE TITLE
PHP 8.0 support status is not updated

### ISSUE THREAD

**Issue by Ahmad-Al-Ali** [Azure/app-service-linux-docs#88]
Please update this https://github.com/Azure/app-service-linux-docs/blob/master/Runtime_Support/php_support.md#php-8 to reflect the status of PHP 8.0, it's currently set to TBD although it's visible on azure portal

**Comment by sweigand** [comment]
The MSSQL/SQLSRV driver isn't included yet (like with 7.3 and/or 7.4), so this is probably a soft launch. Heck, when I talked with Microsoft Azure on July 15 they couldn't tell me a date as to when PHP8 would be available and on July 29 it shows.
